# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='data',
            field=models.CharField(default='09 de setembro de 2017', max_length=255),
        ),
        migrations.AddField(
            model_name='projetos',
            name='github',
            field=models.CharField(default='https://github.com/seurepositorio', max_length=100),
        ),
        migrations.AddField(
            model_name='projetos',
            name='linguagem',
            field=models.CharField(default='Linguagem', max_length=100),
        ),
        migrations.AddField(
            model_name='projetos',
            name='name',
            field=models.CharField(default='Seu nome', max_length=50),
        ),
        migrations.AddField(
            model_name='projetos',
            name='nome',
            field=models.CharField(default='Nome do Projeto', max_length=50),
        ),
        migrations.AddField(
            model_name='projetos',
            name='sobre',
            field=models.CharField(default='Sobre', max_length=255),
        ),
    ]
