# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 22:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20170823_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projetos',
            new_name='projeto',
        ),
    ]
