# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20170823_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='sobre',
            field=models.CharField(max_length=700, verbose_name='Sobre'),
        ),
    ]
